#!/bin/bash

TOKEN=$GITHUB_TOKEN
DEPLOY_KEY=$GITHUB_DEPLOY_KEY
REPO_SLUG=$TRAVIS_REPO_SLUG
COMMIT=$TRAVIS_COMMIT
TOKEN_NAME="GITHUB_TOKEN"
DEPLOY_KEY_NAME="GITHUB_DEPLOY_KEY"
ENV_NAME="Travis"
GIT_USERNAME="Deployment Bot (Travis)"
GIT_EMAIL="deploy@travis-ci.org"
